<?php

$current_category_id = $block->getCurrentCategoryId();
$categoryObj = $this->categoryRepository->get($current_category_id);
$subcategories = $categoryObj->getChildrenCategories();

?>

<ul class="subcategories">

<?php 

foreach($subcategories as $subcat) {
	$categoryData = $this->getCategoryData($subcat->getId());
	$image_filename = $categoryData['category_thumb'];
	$image_folder = $this->getUrl('pub/media').'catalog/category/';
	$image_complete = $image_folder.$image_filename;
		
?>

    <li class="sub-category">
		<a href="<?php echo $subcat->getUrl(); ?>"><?php echo $subcat->getName(); ?><BR>
    	<?php if($image_filename != ''){?><img src="<?php echo $image_complete ?>" alt="<?php echo $subcat->getName(); ?>" /></a> <?php }?>
        
    </li>
    
<?php } ?>

</ul>
